"""Repository ports — persistence interfaces (Protocols). Impls: ``ampere.adapters.repos``.

Kept as thin CRUD-ish contracts; the daily use-case (``run_daily``) composes them transactionally
per ``snapshot_date`` for idempotency (SC6).
"""

from __future__ import annotations

from datetime import date
from typing import Protocol

from ampere.domain.models import Chipset, Device, Listing, Score


class ChipsetRepo(Protocol):
    def get(self, chipset_id: str) -> Chipset | None: ...
    def all(self) -> list[Chipset]: ...
    def upsert(self, chipset: Chipset) -> None: ...


class DeviceRepo(Protocol):
    def get(self, device_id: str) -> Device | None: ...
    def all(self) -> list[Device]: ...
    def upsert(self, device: Device) -> None: ...


class AliasRepo(Protocol):
    def lookup(self, raw_pattern: str) -> str | None: ...
    def remember(self, raw_pattern: str, device_id: str) -> None: ...


class ListingRepo(Protocol):
    def for_snapshot(self, snapshot_date: date) -> list[Listing]: ...
    def replace_snapshot(self, snapshot_date: date, listings: list[Listing]) -> None:
        """Atomically delete + rewrite all listings for the date (idempotent, SC6)."""
        ...


class ScoreRepo(Protocol):
    def for_snapshot(self, snapshot_date: date) -> list[Score]: ...
    def replace_snapshot(self, snapshot_date: date, scores: list[Score]) -> None: ...


class RunRepo(Protocol):
    def last_successful(self) -> date | None: ...
    def start(self, snapshot_date: date, source_kind: str) -> int: ...
    def finish(self, run_id: int, *, status: str, listing_count: int) -> None: ...
